eureka:
  instance:
    #hostname: registry
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      #defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

spring:
  rabbitmq:
    #host: rabbitmq
    host:localhost
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
      
  #一直没生效
  jpa:
    hibernate:
      ddl-auto: none
        #create：每次加载hibernate会自动创建表，以后启动会覆盖之前的表，所以这个值基本不用，严重会导致的数据的丢失。
        #create-drop ： 每次加载hibernate时根据model类生成表，但是sessionFactory一关闭，表就自动删除，下一次启动会重新创建。默认值。
        #update：加载hibernate时根据实体类model创建数据库表，这是表名的依据是@Entity注解的值或者@Table注解的值，sessionFactory关闭表不会删除，且下一次启动会根据实体model更新结构或者有新的实体类会创建新的表。
        #validate：启动时验证表的结构，不会创建表
        #none：启动时不做任何操作
    properties:
      hibernate:
        show-sql: true
    generate-ddl: true
    #指定目标数据库
    #database: org.hibernate.dialect.MySQL5Dialect
    #指定目标数据库的类型.
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

authserver:
    #hostname: auth-service
    hostname: localhost
    port: 5000
    contextPath: /uaa

security:
  oauth2:
    resource:
      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current
